E_commerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('seller_app/', include('seller_app.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('customer_app/', include('customer_app.urls')),
   
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from . import views
app_name='common'

urlpatterns=[
    path('base',views.common_base,name='base'),
    path('index',views.common_index,name='home'),
    path('customer_login',views.common_customer_login,name='customer_login'),
    path('customer_register',views.common_customer_register,name='cus_register'),
    path('seller_register',views.common_seller_register,name='seller_register'),
    path('seller_login',views.common_seller_login,name='seller_login'),
]

common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    customer_name = models.CharField(max_length=20)
    email = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    phone = models.BigIntegerField()
    gender = models.CharField(max_length=15)
    password = models.CharField(max_length=10,default='')
    status = models.CharField(max_length=20, default='active')



class Seller(models.Model):
    seller_name = models.CharField(max_length=20)
    email = models.CharField(max_length=15)
    address = models.CharField(max_length=200)
    phone = models.BigIntegerField()
    user_name = models.IntegerField(default=0)
    password = models.CharField(max_length=40, default='')
    gender = models.CharField(max_length=15)
    company_name = models.CharField(max_length=50)
    holder_name = models.CharField(max_length=20)
    ifsc = models.CharField(max_length=50)
    branch = models.CharField(max_length=50)
    account_number = models.BigIntegerField()
    image = models.ImageField(upload_to='seller/',default='')
    status = models.CharField(max_length=20, default='pending')

    class Meta:
        db_table = 'seller'

common/views.py
from django.shortcuts import render
from django.http import HttpResponse
from.models import Customer, Seller
# Create your views here.

def common_base(request):
    return render(request,'common_templates/base.html')
def common_index(request):
    return render(request,'common_templates/index.html')
def common_customer_login(request):
    return render(request,'common_templates/customer_login.html')
def common_customer_register(request):
    if request.method == 'POST':
        cname = request.POST['customer_name']
        email = request.POST['email']
        address = request.POST['address']
        phone = request.POST['phone']
        gender = request.POST['gender']
        password = request.POST['password']

        customer = Customer(customer_name = cname, email = email, address = address, phone = phone, gender = gender, password = password)
        customer.save()
    return render(request,'common_templates/customer_register.html')


def common_seller_register(request):
    if request.method == 'POST':
        sname = request.POST['seller_name']
        semail = request.POST['email']
        saddress = request.POST['address']
        sphone = request.POST['phone']
        sgender = request.POST['gender']
        scompany_name = request.POST['company_name']
        sholder_name = request.POST['holder_name']
        sifsc = request.POST['ifsc']
        sbranch = request.POST['branch']
        sacc_no = request.POST['account_number']
        simage = request.FILES['image']

        seller = Seller(seller_name = sname, email=semail, address=saddress, phone=sphone, gender=sgender, company_name=scompany_name, holder_name=sholder_name, ifsc=sifsc, branch=sbranch, account_number=sacc_no, image=simage)
        seller.save()
        

    return render(request,'common_templates/seller_register.html')

def common_seller_login(request):
    return render(request,'common_templates/seller_login.html')

common/templates/common_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">

    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

    {% block header %}

    {% endblock %}

    <title>{% block title %}base{% endblock %}</title>
</head>

<body>
    <nav class="navbar">
        <div class="container" style="justify-content: center;">
            <div class="row">
                <div class="col-12">
                    <div class="navbarHeading">
                        <a class="navbar-brand">ONLINE SHOPPING WEBSITE</a>
                    </div>

                </div>
            </div>
        </div>
    </nav>




    {% block content %}{% endblock %}
    

    <footer class="mt-5 pt-5 pb-5 footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-xs-12">
                    <a class="navbar-brand fs-2 fw-bold" href="#"><span class="text-danger">ONLINE SHOPPING
                            WEBSITE</span>
                    </a>
                    <p class="footer_content">NO.1 e-commerce company, headquartered in Bengaluru, and
                        incorporated in Singapore as a
                        private limited company.The company initially focused on
                        electronics, fashion, home essentials, groceries, and lifestyle products.</p>
                    <ul class="social">
                        <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                        <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                        <li><a href="#"><i class="bi bi-whatsapp"></i></a></li>
                        <li><a href="#"><i class="bi bi-instagram"></i></a></li>
                    </ul>
                </div>

                <div class="col-lg-6 col-xs-12 links">
                    <h4 class="mt-lg-0 mt-sm-3">Quick Links</h4>
                    <ul class="m-0 p-0">
                        <li><a href="{% url 'common:home' %}">Home</a></li>
                        <li><a href="">About Us</a></li>
                        <li><a href="">Connect With Us</a></li>
                        <li><a href="">Our Company</a></li>
                        <li><a href="">Privacy and Cookes Policy</a></li>
                        <li><a href="">Follow Us</a></li>

                    </ul>

                </div>

            </div>
            <div class="row mt-5 lastsection">
                <div class="col copyright text-center">
                    <p>
                        <small class="text-white-50">
                            Ⓒ 2022 ONLINE SHOPPING. All Right Reserved
                        </small>
                    </p>
                </div>

            </div>
        </div>

    </footer>





</body>

</html>

common/templates/common_templates/customer_login.html
{% extends 'common_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_customer_login.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<section id="loginPage">

    <section class="login py-5" style="    margin-bottom: -48px;">
        <div class="container">
            <div class="row g-0" id="log">
                <div class="col-lg-5">
                    <img src="{% static 'images/cart1.webp' %}" class="img-fluid" alt="">
                </div>
                <div class="col-lg-7 text-center py-5">
                    <h1>CUSTOMER LOGIN</h1>

                    <form>
                        <div class="form-row py-3 pt-5">
                            <div class="offset-1 col-lg-10">
                                <input type="email" class="inp px-3" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-row py-3">
                            <div class="offset-1 col-lg-10">
                                <input type="password" class="inp px-3" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-row py-3">
                            <div class="offset-1 col-lg-10">
                                <button class="btn"><a href="#">Login</a></button>
                            </div>
                        </div>
                        <a class="createAcc" href="">Forgot password</a>
                    </form>

                    <p class="question">Don't have an account?</p>
                    <a class="createAcc" href="{% url 'common:cus_register' %}">Create an account.</a>
                </div>
            </div>
        </div>
    </section>



    <!-- footer -->

    {% endblock %}

common/templates/common_templates/customer_register.html
{% extends 'common_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_customer_register.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<section id="main_body">


    <div class="heading" style="padding-top: 66px;">
        <h1 class="heading_text text-center mb-2"><u>CUSTOMER REGISTRATION</u> </h1>
    </div>


    <section id="reg_form">
        <div class="container">
            <div class="row justify-content-center mt-5">
                <div class="col-xs-12 col-sm-8 col-md-6 col-lg-5">
                    <div class="card" style="box-shadow: 12px 12px 22px;">
                        <div class="card-header">
                            <h5 class="card-title">Register</h5>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="">Name</label>
                                    <input type="text" name="customer_name" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">Email</label>
                                    <input type="email" name='email' class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">Address</label><br>
                                    <textarea style="font-size: 20px;" name="address" name="remark" id="" cols="30"
                                        rows="4" placeholder="Write here..."></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="">Phone Number</label>
                                    <input type="number" pattern="\d*" name="phone" class="form-control" />
                                </div>
                                <div class="form-group">

                                    <label for="">Gender </label> <br>
                                    &nbsp;
                                    <input type="radio" name="gender" value="male" />Male
                                    &nbsp;
                                    <input type="radio" name="gender" value="female" />Female
                                    &nbsp;
                                    <input type="radio" name="gender" value="others" />Others



                                </div>
                                <div class="form-group">
                                    <label for="">Password</label>
                                    <input type="password" name='password' class="form-control" />
                                </div>

                                <button type="submit" class="btn btn-outline-success form-control mt-3" id="btnColor">
                                    Register
                                </button>
                            </form>
                            <br>
                            <p class="text-left" style="font-size:15px">If you already have an account,
                                <a href="{% url 'common:customer_login' %}">login</a> instead.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</section>





<!-- footer -->

{% endblock %}

common/templates/common_templates/index.html
{% extends 'common_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_index.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}


<section id="banner_image">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="banner">
                    <img src="{% static 'images/banner.jpg' %}" class="img-fluid" alt="" class="profile-img">

                    <div class="inner">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-12" style="margin-bottom: -62px;">
                                    <div id="twoButtons">
                                        <a href="{% url 'common:customer_login' %}" style="text-decoration: none;"><button
                                                class="firstBtn firstButton">CUSTOMER</button></a>
                                        <a href="{% url 'common:seller_login' %}" style="text-decoration: none;"><button class="firstBtn secondBtn">SELLER</button></a>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

</section>




<!-- footer -->

{% endblock %}

common/templates/common_templates/seller_login.html
{% extends 'common_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_seller_login.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<section id="loginPage">

    <section class="login py-5" style=" margin-bottom: -48px;">
        <div class="container">
            <div class="row g-0" id="log">
                <div class="col-lg-5">
                    <img src="{% static 'images/sellerlogin.jpg' %}" class="img-fluid" alt="">
                </div>
                <div class="col-lg-7 text-center py-5">
                    <h1>SELLER LOGIN</h1>

                    <form>
                        <div class="form-row py-3 pt-5">
                            <div class="offset-1 col-lg-10">
                                <input type="email" class="inp px-3" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-row py-3">
                            <div class="offset-1 col-lg-10">
                                <input type="password" class="inp px-3" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-row py-3">
                            <div class="offset-1 col-lg-10">
                                <button class="btn"><a href="#">Login</a></button>
                            </div>
                        </div>
                        <a class="createAcc" href="">Forgot password</a>
                    </form>

                    <p class="question">Don't have an account?</p>
                    <a class="createAcc" href="{% url 'common:seller_register' %}">Create an account.</a>
                </div>
            </div>
        </div>
    </section>



    <!-- footer -->

    {% endblock %}

common/templates/common_templates/seller_register.html
{% extends 'common_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_seller_register.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<section id="main_body">


    <div class="heading" style="padding-top: 66px;">
        <h1 class="heading_text text-center mb-2"><u>SELLER REGISTRATION</u> </h1>
    </div>


    <section id="reg_form">
        <div class="container">
            <div class="row justify-content-center mt-5">
                <div class="col-xs-12 col-sm-8 col-md-6 col-lg-5">
                    <div class="card" style="box-shadow: 12px 12px 22px;">
                        <div class="card-header">
                            <h5 class="card-title">Register</h5>
                        </div>
                        <div class="card-body">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="">Name</label>
                                    <input type="text" name="seller_name" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">Email</label>
                                    <input type="email" name='email' class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">Address</label><br>
                                    <textarea style="font-size: 20px;" name="address" name="remark" id="" cols="30"
                                        rows="4" placeholder="Write here..."></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="">Phone Number</label>
                                    <input type="number" name="phone" pattern="\d*" class="form-control" />
                                </div>
                                <div class="form-group">

                                    <label for="">Gender </label> <br>
                                    &nbsp;
                                    <input type="radio" name="gender" value="male" />Male
                                    &nbsp;
                                    <input type="radio" name="gender" value="female" />Female
                                    &nbsp;
                                    <input type="radio" name="gender" value="others" />Others



                                </div>
                                <div class="form-group">
                                    <label for="">Company Name</label>
                                    <input type="text" name='company_name' placeholder="Company Name"
                                        class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">Account Holder Name</label>
                                    <input type="text" name="holder_name" placeholder="Account Holder Name"
                                        class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">IFSC</label>
                                    <input type="text" name="ifsc" placeholder="IFSC NO" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">Branch</label>
                                    <input type="text" name="branch" placeholder="Bank Branch" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">Account Number</label>
                                    <input type="number" name="account_number" placeholder="Account Number"
                                        class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="">Seller image</label>
                                    <input type="file" value="image" name="image" class="form-control" />
                                </div>



                                <button class="btn btn-outline-success form-control mt-3" id="btnColor">
                                    Register
                                </button>
                            </form>
                            <br>
                            <p class="text-left" style="font-size:15px">If you already have an account, <a
                                    href="{% url 'common:seller_login' %}">login</a> instead.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</section>





<!-- footer -->

{% endblock %}