E_commerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('seller_app/', include('seller_app.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('customer_app/', include('customer_app.urls')),
   
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin_app/urls.py
from django.urls import path
from . import views
app_name='admin_app'

urlpatterns=[
    path('base',views.admin_app_base,name='admin_base'),
    path('admin_home',views.admin_app_admin_home,name='ahome'),
    path('seller_details',views.admin_app_seller_details,name='dseller'),
    path('approve',views.admin_app_approve,name='approve'),
    path('customer_details',views.admin_app_customer_details,name='dcustomer'),


]

common/urls.py
from django.urls import path
from . import views
app_name='common'

urlpatterns=[
    path('base',views.common_base,name='base'),
    path('index',views.common_index,name='home'),
    path('customer_login',views.common_customer_login,name='customer_login'),
    path('customer_register',views.common_customer_register,name='cus_register'),
    path('seller_register',views.common_seller_register,name='seller_register'),
    path('seller_login',views.common_seller_login,name='seller_login'),
]

admin_app/models.py
from django.db import models

# Create your models here.

admin_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from common.models import Seller
from django.core.mail import send_mail
from random import randint
from django.conf import settings
# Create your views here.



def admin_app_base(request):
    return render(request,'admin_app_templates/base.html')

def admin_app_admin_home(request):
    return render(request,'admin_app_templates/admin_home.html')

def admin_app_seller_details(request):
    sellers = Seller.objects.filter(status = 'approved')
    return render(request,'admin_app_templates/seller_details.html',{'sellers_list':sellers})


def admin_app_approve(request):
    sellers = Seller.objects.filter(status = 'pending')

    if request.method == 'POST':
        seller_id = request.POST['seller_id']
        seller = Seller.objects.get(id = seller_id)

        if 'approve' in request.POST:
            # logic when approve button clicked
           
            
            seller.status = 'approved' #sql update query
            seller.save()
            user_name = randint(1111,9999)
            password = 'sel-' + str(user_name) + str(seller.phone)[5:]
            mail_subject = "Account Approval"
            message_body = "Hi your account has been approved by Admin, You can now login with username" + str(user_name) + " and temprorary password" + password

            
        if 'reject' in request.POST:

            seller.status = 'reject' 
            seller.save()
            
            mail_subject = "Account Rejected"
            message_body = "sorry we cannot approve your request"

        send_mail(
            subject = mail_subject,
            message = message_body,
            from_email = settings.EMAIL_HOST_USER,
            recipient_list= [seller.email]
            )
            


    return render(request,'admin_app_templates/approve.html',{'sellers_list':sellers})

# ///////////////////////////////////////////////////////////////////////////////
def admin_app_customer_details(request):
    return render(request,'admin_app_templates/customer_details.html')

admin_app/templates/admin_app_templates/admin_home.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_admin_home.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<!-- header -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">

                        <img src="{% static 'images/favorites.png' %}" alt="">
                        <h5 class="card-title">Approve Seller</h5>

                        <button class="btn btn-success"><a href="">View</a></button>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{% static 'images/bussiness-man.png' %}" alt="">
                        <h5 class="card-title">View Seller</h5>

                        <button class="btn btn-success"><a href="">View</a></button>

                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{% static 'images/teamwork.png' %}" alt="">
                        <h5 class="card-title">View Customer</h5>

                        <button class="btn btn-success"><a href="">View</a></button>
                    </div>
                </div>
            </div>

            <!-- <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{% static 'images/checkout.png' %}" alt="">
                        <h5 class="card-title">View Order</h5>

                        <button class="btn btn-success"><a href="">View</a></button>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{% static 'images/arrow.png' %}" alt="">
                        <h5 class="card-title">Recent</h5>

                        <button class="btn btn-success"><a href="">View</a></button>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{% static 'images/find.png' %}" alt="">
                        <h5 class="card-title">Card title</h5>

                        <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{% static 'images/fired.png' %}" alt="">
                        <h5 class="card-title">Card title</h5>

                        <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{% static 'images/rejection.png' %}" alt="">
                        <h5 class="card-title">Card title</h5>

                        <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{% static 'images/remove.png' %}" alt="">
                        <h5 class="card-title">Card title</h5>

                        <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
            </div> -->
        </div>
    </div>
</section>


<!-- footer -->

{% endblock %}

admin_app/templates/admin_app_templates/approve.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_approve.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<!-- header -->
<section id="header">
    <div class="heading">
        <h1>Approve Seller</h1>
    </div>
    <div class="table_responsive">
        <table>
            <thead>
                <tr>
                    <th>Sl.No</th>
                    <th>Seller pic</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>AccHolder</th>
                    <th>Branch</th>
                    <th>IFSC</th>
                    <th>Acc.No</th>
                    <th>Approve</th>
                    <th>Reject</th>
                </tr>
            </thead>

            <tbody>

                {% for seller in sellers_list %}
                <form method="POST" >
                    {% csrf_token %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><img src="{{ seller.image.url}}" alt=""></td>
                        <td>{{ seller.seller_name }}</td>
                        <td>{{ seller.email }}</td>

                        <td>{{ seller.phone }}</td>
                        <td>{{ seller.address }}</td>
                        <td>{{ seller.holder_name }}</td>
                        <td>{{ seller.branch }}</td>
                        <td>{{ seller.ifsc }}</td>
                        <td>{{ seller.account_number }}</td>
                        <td><button class="btn btn-success" name = 'approve' type="submit">Approve</button></td>
                        <td><button class="btn btn-danger" name = 'reject' type="submit">Reject</button></td>
                        <td><input type="hidden" name="seller_id" value={{seller.id}}></td>

                    </tr>

                </form>

                {% endfor %}
            </tbody>
        </table>
    </div>


</section>


<!-- footer -->

{% endblock %}

admin_app/templates/admin_app_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">

    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

    {% block header %}

    {% endblock %}

    <title>{% block title %}base{% endblock %}</title>
</head>

<body>

    <!-- <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Admin</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav" style="margin-left: 65px;font-size: 20px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'admin_app:ahome' %}">Home</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Profile
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'admin_app:approve' %}">Approve Seller</a></li>
                            <li><a class="dropdown-item" href="{% url 'admin_app:dseller' %}">View Seller</a></li>
                            <li><a class="dropdown-item" href="#">View Customer</a></li>
                            <li><a class="dropdown-item" href="#">View Order</a></li>
                            <li><a class="dropdown-item" href="#">Recent Update</a></li>
                            <li><a class="dropdown-item" href="#">View Product</a></li>
                            <li><a class="dropdown-item" href="#">Remove Seller</a></li>
                            <li><a class="dropdown-item" href="#">Remove Customer</a></li>
                            <li><a class="dropdown-item" href="#">Remove Product</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav> -->

    <nav class="navbar navbar-expand-sm navbar-dark ">
        <div class="container-fluid">
            <a class="navbar-brand" href="javascript:void(0)">Admin</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav me-auto" style="background-color: black;">
                    <li class="nav-item" style="    margin-left: 20px;">
                        <a class="nav-link" href="">Home</a>
                    </li>
                    <li class="nav-item" style="    margin-left: 20px;">
                        <a class="nav-link" href="{% url 'admin_app:approve' %}">Approve Seller</a>
                    </li>
                    <li class="nav-item" style="    margin-left: 20px;">
                        <a class="nav-link" href="{% url 'admin_app:dseller' %}">View Seller</a>
                    </li>
                    <li class="nav-item" style="    margin-left: 20px;">
                        <a class="nav-link" href="">View Customer</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>









    {% block content %}{% endblock %}


    <footer class="mt-5 pt-5 pb-5 footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-xs-12">
                    <a class="navbar-brand fs-2 fw-bold" href="#"><span class="text-danger">ONLINE SHOPPING
                            WEBSITE</span>
                    </a>
                    <p class="footer_content">NO.1 e-commerce company, headquartered in Bengaluru, and
                        incorporated in Singapore as a
                        private limited company.The company initially focused on
                        electronics, fashion, home essentials, groceries, and lifestyle products.</p>
                    <ul class="social">
                        <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                        <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                        <li><a href="#"><i class="bi bi-whatsapp"></i></a></li>
                        <li><a href="#"><i class="bi bi-instagram"></i></a></li>
                    </ul>
                </div>

                <div class="col-lg-6 col-xs-12 links">
                    <h4 class="mt-lg-0 mt-sm-3">Quick Links</h4>
                    <ul class="m-0 p-0">
                        <li><a href="{% url 'common:home' %}">Home</a></li>
                        <li><a href="">About Us</a></li>
                        <li><a href="">Connect With Us</a></li>
                        <li><a href="">Our Company</a></li>
                        <li><a href="">Privacy and Cookes Policy</a></li>
                        <li><a href="">Follow Us</a></li>

                    </ul>

                </div>

            </div>
            <div class="row mt-5 lastsection">
                <div class="col copyright text-center">
                    <p>
                        <small class="text-white-50">
                            Ⓒ 2022 ONLINE SHOPPING. All Right Reserved
                        </small>
                    </p>
                </div>

            </div>
        </div>

    </footer>





</body>

</html>

admin_app/templates/admin_app_templates/customer_details.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_customer_details.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<!-- header -->
<section id="header">
    <div class="heading">
        <h1>Customer Details</h1>
    </div>
    <div class="table_responsive">
        <table>
            <thead>
                <tr>
                    <th>Sl.No</th>

                    <th>Name</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>Gender</th>
                    <th>Password</th>



                </tr>
            </thead>

            <tbody>
                <form method="POST">
                    {% csrf_token %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ customer.seller_name }}</td>
                        <td>{{ customer.email }}</td>
                        <td>{{ customer.address }}</td>
                        <td>{{ customer.phone }}</td>
                        <td>{{ customer.gender }}</td>
                        <td>{{ customer.password }}</td>
                    </tr>

                </form>
            </tbody>
        </table>
    </div>


</section>


<!-- footer -->

{% endblock %}

admin_app/templates/admin_app_templates/seller_details.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_seller_details.css' %}">
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<!-- header -->
<section id="header">
    <div class="heading">
        <h1>View Seller Details</h1>
    </div>
    <div class="table_responsive">
        <table>
            <thead>
                <tr>
                    <th>Sl.No</th>
                    <th>Seller pic</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>AccHolder</th>
                    <th>Branch</th>
                    <th>IFSC</th>
                    <th>Acc.No</th>

                </tr>
            </thead>

            <tbody>
                {% for seller in sellers_list %}
                <form method="POST">
                    {% csrf_token %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><img src="{{ seller.image.url}}" alt=""></td>
                        <td>{{ seller.seller_name }}</td>
                        <td>{{ seller.email }}</td>

                        <td>{{ seller.phone }}</td>
                        <td>{{ seller.address }}</td>
                        <td>{{ seller.holder_name }}</td>
                        <td>{{ seller.branch }}</td>
                        <td>{{ seller.ifsc }}</td>
                        <td>{{ seller.account_number }}</td>



                    </tr>

                </form>
                {% endfor %}
            </tbody>
        </table>
    </div>


</section>


<!-- footer -->

{% endblock %}